services:
  mysql:
    image: mysql:8.0
    container_name: api_nest_test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_api_nest
      MYSQL_USER: evandroooff
      MYSQL_PASSWORD: Teste@pi1
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - minha_rede

networks:
  minha_rede:
    driver: bridge
